
const faqData = [
    {
        title: "What is QR Code?",
        body: "A QR code (Quick Response code) is a type of barcode that can be scanned using a smartphone camera or QR code scanner to quickly access information, such as URLs, contact details, or Wi-Fi credentials."
    },
    {
        title: "How does the QR code generator work?",
        body: "Simply select the type of QR code you want to create, like for a website link, contact details, or Wi-Fi. Enter the relevant information, and the app will generate a QR code for you to download and share."
    },
    {
        title: "Is this QR code generator free?",
        body: "Yes, our app is completely free to use for creating various types of QR codes, including for Wi-Fi, links, contacts, and more."
    },
    {
        title: "Do I need an account to generate a QR code?",
        body: "No account or sign-up is required. You can start generating QR codes instantly, hassle-free!"
    },
    {
        title: "How do I create a Wi-Fi QR code?",
        body: "Choose the 'Wi-Fi' option, enter your Wi-Fi network name (SSID) and password, and select the security type. The app will generate a QR code that lets users join your Wi-Fi network with a simple scan."
    },
    {
        title: "Is my Wi-Fi information secure in the app?",
        body: "Yes, your Wi-Fi credentials are only used to generate the QR code and are not stored or shared by our app."
    },
    {
        title: "What types of QR codes can I create?",
        body: "You can create QR codes for website URLs, Wi-Fi networks, contact details, email addresses, and more."
    },
    {
        title: "Can I customize the QR codes?",
        body: "Currently, we offer simple, easy-to-scan QR codes that prioritize readability and ease of use. Future updates may include additional customization options."
    },
    {
        title: "How do I scan a QR code?",
        body: "Most smartphone cameras can scan QR codes directly. Just open your camera, point it at the QR code, and tap the notification that appears."
    },
    {
        title: "What devices are compatible with the generated QR codes?",
        body: "The QR codes can be scanned by any device with a QR scanner, including most iOS, Android, and tablet devices."
    },
    {
        title: "How long do the QR codes last?",
        body: "QR codes generated by our app do not expire, so you can use them indefinitely."
    },
    {
        title: "Can I save or print the QR codes?",
        body: "Yes, you can download the QR code as an image and save it to your device. You can also print it to display or share offline."
    }
];



export default faqData;